### ISSUE TITLE
returning NA from Ecoflora

### ISSUE THREAD

**Issue by GioBo** [GioBo/TR8#67]
Structure of ECOFLORA web pages has changes, thus TR8 does not find data -> method 'retrieve' has to be adapted to the new structure

**Comment by GioBo** [comment]
a <- tr8(c("Aconitum lycoctonum subsp. vulparia"),download_list=c("h_max"))

still causes problems

**Comment by tanjakofodpetersen** [comment]
Hi, this seems to still be the case - seemingly, the domain of Ecoflora has changed (from http://www.ecoflora.co.uk/ to http://ecoflora.org.uk/). Could this be the issue? If yes, is there any way to redirect?

**Comment by GioBo** [comment]
Uhmmm... I've tried and it seems to work; what version of the package are you using (just type `sessionInfo()` after having loaded TR8)?
Thanks,

G.

**Comment by tanjakofodpetersen** [comment]
I am using version 0.9.18.
Hm, if it is working for you, I assume it must be a mistake in my code somewhere. I will have to keep looking. Thanks for the fast reply!
