### ISSUE TITLE
Cannot library(TR8)

### ISSUE THREAD

**Issue by zicrac** [GioBo/TR8#69]
Hello,

I used the TR8 to find traits today. 

The first 2 hours was all right. However from about 8 pm , the function seems not working and when I tried to library(TR8), the R studio just paralyzed and could not library successfully. Could you please give me advice about this problem?

Thank you. 

Zhe 

![cannot library tr8](https://user-images.githubusercontent.com/39935783/40952975-448d7294-6843-11e8-8151-d2bdeb0e769a.png)

**Comment by GioBo** [comment]
Hi, 
 
    I cannot reproduce this issue: are you still facing it? 
   If so, could you please try TR8 in outside R Studio?

**Comment by zicrac** [comment]
I found the problem. It's a mac version stuff. 

After installing Xquartz software, there's no bugs.

Thanks.
